"""initial

Revision ID: c44acc20170b
Revises: 
Create Date: 2025-11-20 21:19:25.658889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44acc20170b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_no', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('shape_and_cut', sa.String(length=255), nullable=False),
    sa.Column('tot_est_weight', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('clarity', sa.String(length=64), nullable=True),
    sa.Column('style_number', sa.String(length=255), nullable=True),
    sa.Column('image_filename', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('isecopy', sa.Boolean(), nullable=True),
    sa.Column('company_logo', sa.String(), nullable=True),
    sa.Column('notice_image', sa.Boolean(), nullable=True),
    sa.Column('igi_logo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_no'), 'reports', ['report_no'], unique=True)
    op.create_index('ix_reports_style_created', 'reports', ['style_number', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_style_number'), 'reports', ['style_number'], unique=False)
    op.create_table('uploaded_pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_no', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_pdfs_id'), 'uploaded_pdfs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_uploaded_pdfs_id'), table_name='uploaded_pdfs')
    op.drop_table('uploaded_pdfs')
    op.drop_index(op.f('ix_reports_style_number'), table_name='reports')
    op.drop_index('ix_reports_style_created', table_name='reports')
    op.drop_index(op.f('ix_reports_report_no'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
